### ISSUE TITLE
Zipato siren NE-NAS-AB02Z.eu

### ISSUE THREAD

**Issue by waddle00** [aartse/athom.zipato#55]
Hi,

My siren NE-NAS-AB02Z.eu is integrate in Homey as a PIR motion sensor NE-NAS-PD01Z.EU.
Could you modify your program for integrate this devise ?
Regards

**Comment by aartse** [comment]
i changed the product id for the NE-NAS-PD01Z.EU according to this website:
https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/735?layout=openhab1

then i copied the existing siren PH-PSE02-1B.EU to NE-NAS-AB02Z.EU. i don't know if this will work for NE-NAS-AB02Z.EU, because i don't have the device in my possession. but can you test it for me? i will update the app soon in the test/beta channel.

**Comment by waddle00** [comment]
Hi,
I tested and it's ok for integration. 

but the adjustment parameters are not in conformity. I think I have to take the parameters of the siren Neo cooolcam
http://manual.zwave.eu/backend/make.php?lang=en&sku=NAS-AB02ZE&cert=ZC10-18096227

Thank for your job

**Comment by karlgrosse** [comment]
Hi, i just bought Homey. Before this change, I was on Zipatile...It used to work but since the new upgrade it doesn't really lots of problem so i decided to buy and try Homey. For now no difficulties to add Z-Wave devices but I have problems with 2 Indoor Siren by Zipato ne-nas-ab02z.eu...I can see it it does associate the product but it shows me PIR motion sensor while i ask for Indoor Siren product. Any clue ?
Thank you in advance for your kind return
Regards,
Karl
PS : by the way is there any way i can include my Zipatile into Homey ?

**Comment by aartse** [comment]
hi @karlgrosse try to install the test version of the app (https://homey.app/a/nl.aartse.zipato/test/). it is work on progress (see the feedback from @waddle00), but the test version fixed the product swap with the PIR motion sensor.

**Comment by aartse** [comment]
should be fixed in 3.3.0
