### ISSUE TITLE
Door/ windows sensor no state

### ISSUE THREAD

**Issue by Owein1977** [aartse/athom.zipato#82]
Hi, I just want to move from Zipato to homey and of course I have 10+ windows/ door sensors. Due to the fact that your work is supporting my old Hw I bought the homey pro… long story short - I’m able to connect the sensors, but the do not report the status to homey…the 4in1 (with the longest distance) works! Really appreciate your work/ assist 
BR
Oli

**Comment by aartse** [comment]
Hi, what is the type number of the door/window sensor? And is it added as a zipato device or a general device?

**Comment by aartse** [comment]
hi, i changed something for this device, i hope this will fix your issue. The problem is that I do not have this device in my possession to reproduce the issue and test the changes. Can you install the test version of the app to check it works for your devices: https://homey.app/nl-nl/app/nl.aartse.zipato/Zipato/test/

when it works i will submit the app to the store.

**Comment by Owein1977** [comment]
Brillant… works perfectly!
Many thx, know I can go ahead with homey

**Comment by aartse** [comment]
thank you, i submitted the app for review at homey, after a couple of day's the app will be released in the app store.
